# Stage 1: base image

FROM python:3.9-slim AS base

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# stage 2: build

FROM base AS build 

COPY main.py .

EXPOSE 5001

CMD [ "python", "main.py" ]

