replicaCount: 2

image:
  repository: grinhauz/flask-aws-monitor
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 5001

aws:
  accessKeyId: "accesskey"
  secretAccessKey: "secret"
  region: "us-east-1"

resources: {}